name: CI
on:
  push:
    branches: [main, release/**]
  pull_request:
    branches: [main, release/**]
concurrency:
  # Only cancel jobs for new commits on PRs, and always do a complete run on other branches (e.g. `main`).
  # See: https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
  group: main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  NODE_VERSION: 18
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Cache setup
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

  run:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Admin UI
          - workspace: admin-ui
            command: lint
          - workspace: admin-ui
            command: test
          - workspace: admin-ui
            command: build
          - workspace: admin-ui
            # Account UI
            command: cy:check-types
          - workspace: account-ui
            command: lint
          - workspace: account-ui
            command: build
          # Keycloak Admin Client
          - workspace: "@keycloak/keycloak-admin-client"
            command: lint
          - workspace: "@keycloak/keycloak-admin-client"
            command: build
          # Keycloak Masthead
          - workspace: keycloak-masthead
            command: lint
          - workspace: keycloak-masthead
            command: build
    steps:
      - name: Restore setup
        uses: actions/cache@v3
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run ${{ matrix.command }} task
        run: npm run ${{ matrix.command }} --workspace=${{ matrix.workspace }}

  dependabot:
    needs: [run]
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge ${{ github.event.number }} --auto --squash --repo ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
